
name: Deploy Risk Systems

on:
  push:
    branches:
      - main
jobs:
    deploy_lambdas:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                lambdas: [module-one]
        steps:
        - name: Deploy to AWS Lambda
          uses: MohamedAkbarally/mono-repo-test/.github/workflows/deployment.yml@main
          with:
            function-name: ${{ matrix.lambdas }}
            secrets: inherit
