
name: Deploy Risk Systems

on:
  push:
    branches:
      - main
      - shadow-*
jobs:
    module-one:
        uses: MohamedAkbarally/mono-repo-test/.github/workflows/deployment.yml@main
        with:
            function-name: module-one
        secrets: inherit
