name: Deploy Production Lambda Function

on:
  workflow_call:
    inputs:
      function-name:
        required: true
        type: string
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
jobs:
  paths-filter:
    runs-on: ubuntu-latest
    outputs:
      haschanged: ${{ steps.filter.outputs.workflows }}
    steps:
    - uses: actions/checkout@v2
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          workflows:
            - '${{ inputs.function-name }}/**'
  build_and_deploy:
    needs: paths-filter
    if: github.event_name == 'push' && github.ref == 'refs/heads/main' && needs.paths-filter.outputs.haschanged == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./${{ inputs.function-name }}
          build-args: RISK_TOOLING_PERSONAL_TOKEN=${{ secrets.RISK_TOOLING_PERSONAL_TOKEN }}
          provenance: false
          push: true
          tags: |
            ${{ steps.login-ecr.outputs.registry }}/${{ inputs.function-name }}:${{ github.sha }}
            ${{ steps.login-ecr.outputs.registry }}/${{ inputs.function-name }}:production
            
            
      - name: Update Lambda function
        run: |
          aws lambda update-function-code \
            --function-name ${{ inputs.function-name }} \
            --image-uri "${{ steps.login-ecr.outputs.registry }}/${{ inputs.function-name }}:production"
