name: shadow

on:
  push:
    branches:
      - shadow
    paths:
      - "module-one/**"
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./module-one
          build-args: RISK_TOOLING_PERSONAL_TOKEN=${{ secrets.RISK_TOOLING_PERSONAL_TOKEN }}
          provenance: false
          push: true
          tags: |
            ${{ steps.login-ecr.outputs.registry }}/module-one:${{ github.sha }}
            ${{ steps.login-ecr.outputs.registry }}/module-one:shadow
            
            
      - name: Update Lambda function
        run: |
          aws lambda update-function-code \
            --function-name module-one \
            --image-uri "${{ steps.login-ecr.outputs.registry }}/module-one:${{ github.sha }}"
